name: Предложение / Feature request
title: "[Feature] "
description: Предложить улучшение LOOM

body:
  - type: markdown
    attributes:
      value: |
        Сначала проверьте [существующие задачи](https://github.com/celestialvibes/FlClash/issues).

  - type: textarea
    id: description
    attributes:
      label: Что нужно изменить?
      description: Кратко опишите ожидаемый результат
    validations:
      required: true
  - type: textarea
    attributes:
      label: Зачем это нужно?
      description: Опишите пользовательский сценарий
    validations:
      required: true
  - type: checkboxes
    id: os-labels
    attributes:
      label: Платформа
      description: Выберите хотя бы одну платформу
      options:
        - label: Android
        - label: macOS
    validations:
      required: true
