script_template: inno_setup.iss
app_id: 473702EA-6B91-47EE-AF3E-0AB23EAC33F1
app_name: LOOM
publisher: LOOM
publisher_url: https://loomvpn.pro
display_name: LOOM
executable_name: LOOM.exe
output_base_file_name: LOOM
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin
